
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/express_db?characterEncoding=UTF-8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: hanyue@#$666
#  mail:
#    host: smtp.163.com #SMTP服务器地址
#    username: snhanyue@163.com    #登陆账号
#    password: Hanyue666 #登陆密码（或授权码）
#    properties:
#      from: snhanyue@163.com
  mail:
    host: smtp.mxhichina.com #SMTP服务器地址
    username: vip@snhanyue.top   #登陆账号
    password: Hanyue666 #登陆密码（或授权码）
    properties:
      from: vip@snhanyue.top
  thymeleaf:
    prefix: classpath:/templates/
kdniao:
  EBusinessID: 1575163
  AppKey: f0c1ba54-540c-491f-a18c-8cb01f6346dc
